services:
    wire-android-build-server:
        build:
            context: .
            dockerfile: docker-agent/AndroidAgent
        image: builder-agent:latest
        container_name: wire-android-build-server
        environment:
            - CUSTOM_FLAVOR=Fdroid
            - BUILD_TYPE=Release
            - PATCH_VERSION=0
            - CLEAN_PROJECT_BEFORE_BUILD=true
            - RUN_APP_UNIT_TESTS=true
            - BUILD_CLIENT=true
            #### Signing Vars (KEYSTORE_PATH's home directory is the wire-android folder inside the docker container, start from there e.g. app/keystorefile.keystore)
            #- SIGN_APK=true
            #- KEYSTORE_PATH=your-path-to-your-keystore-file
            #- KSTOREPWD=your-keystore-password
            #- KEYPWD=your-key-password
            #- KEYSTORE_KEY_NAME=your-key-name
            #### Debug Optins
            - BUILD_WITH_STACKTRACE=true
            # For permissions isues with GHA
        user: "${UID}:${GID}"
        volumes:
            - ".:/home/android-agent/wire-android-reloaded"
        command: bash -c "cd /home/android-agent/wire-android-reloaded && /home/android-agent/wire-android-reloaded/docker-agent/configure-project.sh && /home/android-agent/wire-android-re/docker-agent/builder.sh"
