name: FDRoid build and test

on: [push]

jobs:
  
  fdroid-build-and-test:
    environment: main
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Gradle Setup
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: "Setup rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "armv7-linux-androideabi,aarch64-linux-android,x86_64-linux-android,i686-linux-android"
      - name: Setup cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Build Android package
        run: |
          cd core-crypto/crypto-ffi
          cargo make copy-android-resources
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: kotlin
          arguments: "android:publishToMavenLocal"

      - name: Pull image to docker hub as cache
        run: docker pull $DOCKER_USERNAME/wire-android-build-server

      - name: Setup build env
        run: docker-compose up -d

#      - name: Tag docker image
#        run: docker tag builder-agent $DOCKER_USERNAME/wire-android-build-server

#      - name: Login to docker hub
#        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

#      - name: Push image to docker hub as cache
#        run: docker push $DOCKER_USERNAME/wire-android-build-server

      - name: Run build env
        run: docker-compose run wire-android-build-server

